version: '3.3'
services:
  mysql:
    container_name: mysql_appos
    image: mysql:8.0.23
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_danish_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: Appos
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Appos.API/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development